apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: hxtt82oqs-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hxtt82oqs-python 
  name: hxtt82oqs-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: hxtt82oqs-python 
